Map<String, String> englishMap = {
  "app.biometric.reason":"Please authenticate to unlock the app",
  "app.dialog.biometric.fail":"Please authenticate to unlock the app",
  "app.dialog.biometric.fail.something":"Something went wrong, Close the app and try again",
  "app.dialog.biometric.fail.try.again":"We couldn't authenticate you, would you like to try again?",
  "app.dialog.biometric.fail.try.again.confirm":"Yes",
  "app.dialog.biometric.fail.try.again.cancel":"Close app",
  "login.title": "Login",
  "login.subtitle": "Enter your NHS Number and password to log into your account",
  "login.input1": "NHS Number",
  "login.input1.hint": "NHS Number here ...",
  "login.input2": "Password",
  "login.input2.hint": "Password here ...",
  "login.button": "Login",
  "invite.toggle.button": "Have an invite code?",
  "invite.title": "Accept Invite",
  "invite.subtitle":
      "Enter your Invite code, NHS Number and create a new password to accept the invite",
  "invite.subtitle.auto":
      "Enter your NHS Number and create a new password to accept the invite",
  "invite.input1": "Invite code",
  "invite.input1.hint": "Invite code here ...",
  "invite.input2": "NHS Number",
  "invite.input2.hint": "NHS Number here ...",
  "invite.input3": "Password",
  "invite.input3.hint": "Password here ...",
  "invite.input4": "Confirm password",
  "invite.input4.hint": "Confirm password here ...",
  "invite.button": "Accept Invite",
  "invite.back.button": "Go Back",
  "invite.back.button.auto": "Login manually",
  "forgotPassword.title": "Forgot Password",
  "forgotPassword.subtitle":
  "Enter your NHS Number and registered Email address to request a password reset",
  "forgotPassword.input1": "NHS Number",
  "forgotPassword.input1.hint": "NHS Number here ...",
  "forgotPassword.input2": "Email Address",
  "forgotPassword.input2.hint": "Email Address here ...",
  "forgotPassword.button": "Request password reset",
  "forgotPassword.back.button": "Back to login",
  "permissions.page.intro.heading": "Welcome to EMA",
  "permissions.page.intro.desc":
      "EMA stands for Empowering Medical Apps.\nThis is a support tool for those suffering from musculoskeletal disorders and was designed and developed for the NHS.",
  "permissions.page.em.heading": "Exercise Monitoring",
  "permissions.page.em.desc":
      "EMA uses your phone\'s front camera for motion recognition, and features Live Exercise Monitoring.\n\nYour permission is required to enable the app to access your camera for this feature.",
  "permissions.page.notifications.heading": "App Notifications",
  "permissions.page.notifications.desc":
  "EMA gives sends you notifications to keep you up-to-date with exercise schedule!\nEMA also sends you alerts and reminders to ensure that you don't miss out on completing your day's assigned exercises.\n\nYour permission is required to enable the app to send notifications for this feature.",
  "permissions.page.biometric.heading": "Biometric Security",
  "permissions.page.biometric.desc":
  "This app can be secured with your biometric data. We recommend that you enable this security feature to protect your personal details.\n\nIf this feature is turned ON, your biometric authentication will be required every time you open the app, and when you wish to view or change your profile details.",
  "permissions.page.begin.text": "Let's explore features",
  "permissions.page.grant.permission.text": "Grant Permission",
  "permissions.page.biometric.text": "Enable",
  "permissions.page.later.permission.text": "Later",
  "permissions.page.biometric.next":"Authenticate",
  "permissions.page.never.ask":"Do not ask again",
  "permissions.page.open.settings":"Go",
  "permissions.page.biometric.reason":"Please authenticate to enable biometric protection",
  "permissions.page.dialog.camera.title":"Camera access denied",
  "permissions.page.dialog.camera.try.again":"Without camera access, You cannot use the app\nPlease enable camera permissions",
  "permissions.page.dialog.camera.try.again.confirm":"Okay",
  "permissions.page.dialog.camera.open.settings":"Without camera access, You cannot use the app\nPlease go to app settings and give permission to the app",
  "permissions.page.dialog.biometric.title":"Biometric authentication failed",
  "permissions.page.dialog.biometric.try.again":"We couldn't authenticate you, would you like to try again?",
  "permissions.page.dialog.biometric.try.again.confirm":"Yes",
  "permissions.page.dialog.biometric.no.support":"Looks like there is no support for biometric authentication on your device",
  "permissions.page.dialog.biometric.no.support.confirm":"Okay",
  "permissions.page.dialog.notifications.title":"Permission required",
  "permissions.page.dialog.notifications.open.settings":"If you would like to receive app notifications, please go to app settings and give permission to the app",
  "home.tasks.noTasks": "No tasks today, please check back tomorrow",
  "home.tasks.label.incomplete": "incomplete exercises",
  "home.tasks.label.partial": "exercises can be improved",
  "home.tasks.label.complete": "completed exercises",
  "home.tasks.actionHelper": "Click to view tasks",
  "home.tasks.actionHelper.download": "Click to download and view tasks",
  "home.reports.noReports":
      'You will see your latest task report here, check back after performing exercises for a day',
  "home.reports.actionHelper": "Click to view all reports",
  "taskList.action.main": "Perform incomplete exercises",
  "taskList.page.header": "Exercises",
  "taskList.item.status.incomplete": "Incomplete",
  "taskList.item.status.partial": "Can be improved",
  "taskList.item.status.complete": "Completed",
  "reports.page.header": "Reports",
  "reports.item.label.score": "Score:",
  "reports.item.label.result": "Result:",
  "reports.item.result.non": "Non adherent",
  "reports.item.result.partial": "Partially adherent",
  "reports.item.result.full": "Fully adherent",
  "about.aboutApp.header": "About the App",
  "about.aboutApp.content": "EMA stands for Empowering Medical Apps and this app is a support tool for patients suffering from back pain, especially designed and developed for the NHS.\n\nEMA facilitates remote access to quality treatment and physiotherapy sessions from registered NHS HCPs (healthcare professionals).",
  "about.em.header": "Live Exercise Monitoring",
  "about.em.content": "Monitoring of exercises done through Artificially Intelligent motion detecting technology to ensure exercises are being done correctly and no further injury is being caused.",
  "about.extra1.header": "Customised for you",
  "about.extra1.content": "Customised exercise programmes by your physiotherapist to improve your posture and alleviate pain.",
  "settings.biometric.dialog.title":"Please authenticate to change this setting",
  "settings.biometric.dialog.cancel":"Cancel",
  "settings.theme.title":"App Theme",
  "settings.theme.dark.name":"Dark",
  "settings.theme.light.name":"Light",
  "settings.theme.system.name":"System",
  "em.outOfFrame.instruction":"Please make sure your entire body is in the frame",
  "taskCompletion.close":"Close",
  "taskCompletion.skip":"Skip this exercise",
  "taskCompletion.retryUpload":"Retry upload"
};

extension Constants on String {
  String get c {
    if (englishMap.containsKey(this)) {
      return englishMap[this]!;
    } else {
      return this;
    }
  }
}
