// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZNTe8h2kfPhnRc9Gw4PP9BztNxohyAK0',
    appId: '1:786650255347:android:0a156d20fb2dddc55d4c86',
    messagingSenderId: '786650255347',
    projectId: 'emaapp-cac83',
    databaseURL: 'https://emaapp-cac83.firebaseio.com',
    storageBucket: 'emaapp-cac83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4vOVVVz-w0SHNySwpKgkAhgJbtvZjDak',
    appId: '1:786650255347:ios:8416d5669fc0b28f5d4c86',
    messagingSenderId: '786650255347',
    projectId: 'emaapp-cac83',
    databaseURL: 'https://emaapp-cac83.firebaseio.com',
    storageBucket: 'emaapp-cac83.appspot.com',
    androidClientId: '786650255347-cfcg5nj8fjro2jsrb40l3upm5rr3hdo9.apps.googleusercontent.com',
    iosClientId: '786650255347-mf2aq3bdi8kje2bhftuu7iqldkuhfq3b.apps.googleusercontent.com',
    iosBundleId: 'com.parallelreality.emaios',
  );
}
